version: "3"
services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile
      target: production
    ports:
      - '9000:9000'
    working_dir: /src
    #command: /src/start.sh
    tty: true
  nginx:
    build: ./nginx
    ports: 
      - '8080:80'
